export const sagaActions = {
    FETCH_OTP: 'FETCH_OTP',
    FETCH_POD_DETAILS: 'FETCH_POD_DETAILS',
    LOGIN: 'LOGIN',
    FETCH_PAYMENT_DETAILS: 'FETCH_PAYMENT_DETAILS',
    FETCH_UTR_DETAILS: 'FETCH_UTR_DETAILS',
	FETCH_UTR_INGESTION: 'FETCH_UTR_INGESTION',
};
