const events = {
    AUTH: {
        ON_CLICK_VERIFY_EMAIL: 'ON_CLICK_VERIFY_EMAIL',
        ON_SELECT_EMAIL_LOGIN: 'ON_SELECT_EMAIL_LOGIN',
        ON_SELECT_SET_PASSWORD: 'ON_SELECT_SET_PASSWORD',
        ON_SUBMIT_SET_PASSWORD: 'ON_CLICK_SET_PASSWORD',
        ON_CLICK_FORGOT_PASSWORD: 'ON_CLICK_FORGOT_PASSWORD',
        ON_SUBMIT_OTP: 'ON_SUBMIT_OTP',
        ON_SUBMIT_PASSWORD: 'ON_SUBMIT_PASSWORD',
        ON_CLICK_RESEND_OTP: 'ON_CLICK_RESEND_OTP',
    },
    HTTP_API_FAILURE: 'HTTP_API_FAILURE',
    HTTP_API_SUCCESS: 'HTTP_API_SUCCESS',
    ON_CLICK_SEARCH: 'ON_CLICK_SEARCH',
    ON_CLICK_DATE_APPLY: 'ON_CLICK_DATE_APPLY',
    ON_CLICK_LOGOUT: 'ON_CLICK_LOGOUT',
    ON_CLICK_LOGIN: 'ON_CLICK_LOGIN',
    ON_CLICK_USER_PROFILE: 'ON_CLICK_USER_PROFILE',
    ON_CLICK_SIDE_MENU: 'ON_CLICK_SIDE_MENU',
    ON_CLICK_REPORT: 'ON_CLICK_REPORT',
    ON_CLICK_BACK_FROM_SEARCH: 'ON_CLICK_BACK_FROM_SEARCH',
    ON_CLICK_BACK_FROM_DATE: 'ON_CLICK_BACK_FROM_DATE',
    ON_CLICK_POD_DOWNLOAD: 'ON_CLICK_POD_DOWNLOAD',
    ON_CLICK_PAYMENT_ADVICE_DOWNLOAD: 'ON_CLICK_PAYMENT_ADVICE_DOWNLOAD',
    ON_CLICK_UTR_CARD: 'ON_CLICK_UTR_CARD',
    ON_CLICK_INVOICE_DOWNLOAD: 'ON_CLICK_INVOICE_DOWNLOAD',
};

export default events;
